export type Position = "GK" | "CB" | "FB" | "DM" | "CM" | "AM" | "WG" | "ST";
export type Mentality = "Cautious" | "Balanced" | "Assertive";
export type OpponentPlan = "Low Block" | "Mid Block" | "High Press" | "Overload Right" | "Protect Lead";
export type MatchPhase = "idle" | "live" | "finished";

export type Player = { id: string; name: string; position: Position; age: number; overall: number; fitness: number; form: number; morale: number; wage: number; value: number; status: "Available" | "Doubtful" | "Unavailable" };
export type Point = { x: number; y: number };
export type FormationPlayer = { playerId: string; label: string; role: string; point: Point };
export type MatchEvent = { id: string; minute: number; kind: "Commentary" | "Chance" | "Goal" | "Card" | "Tactical"; text: string; detail: string; side: "home" | "away" };
export type MarketTarget = Player & { club: string; league: string; asking: number; availability: "Available" | "Interested" | "Difficult"; scoutStatus: "Unscouted" | "Monitoring" | "Report ready" };
export type Bid = { id: string; targetId: string; amount: number; status: "Submitted" | "Countered" | "Accepted" | "Rejected"; createdAt: string };

export const players: Player[] = [
  { id: "p1", name: "Marek Varga", position: "GK", age: 27, overall: 76, fitness: 94, form: 7.2, morale: 78, wage: 2200, value: 800000, status: "Available" },
  { id: "p2", name: "Jonas Bell", position: "CB", age: 24, overall: 74, fitness: 91, form: 7.0, morale: 82, wage: 1800, value: 650000, status: "Available" },
  { id: "p3", name: "Sami Okoro", position: "CB", age: 29, overall: 78, fitness: 87, form: 7.4, morale: 75, wage: 2600, value: 900000, status: "Available" },
  { id: "p4", name: "Elias Hart", position: "FB", age: 22, overall: 71, fitness: 96, form: 6.8, morale: 86, wage: 1400, value: 430000, status: "Available" },
  { id: "p5", name: "Tomas Ilic", position: "DM", age: 31, overall: 79, fitness: 84, form: 7.1, morale: 77, wage: 3100, value: 520000, status: "Available" },
  { id: "p6", name: "Noah Mensah", position: "CM", age: 23, overall: 77, fitness: 89, form: 7.6, morale: 91, wage: 2300, value: 1200000, status: "Available" },
  { id: "p7", name: "Rui Duarte", position: "AM", age: 26, overall: 81, fitness: 92, form: 7.8, morale: 88, wage: 4200, value: 2100000, status: "Available" },
  { id: "p8", name: "Luka Baresic", position: "WG", age: 20, overall: 73, fitness: 90, form: 7.3, morale: 84, wage: 1600, value: 980000, status: "Available" },
  { id: "p9", name: "Isaac Cole", position: "WG", age: 25, overall: 75, fitness: 79, form: 6.9, morale: 69, wage: 2500, value: 760000, status: "Doubtful" },
  { id: "p10", name: "Matteo Riva", position: "ST", age: 28, overall: 83, fitness: 93, form: 8.1, morale: 94, wage: 5100, value: 2500000, status: "Available" },
  { id: "p11", name: "Adem Kaya", position: "CM", age: 19, overall: 68, fitness: 98, form: 7.0, morale: 89, wage: 900, value: 320000, status: "Available" },
];

const points = { gk: { x: 8, y: 50 }, cb1: { x: 23, y: 30 }, cb2: { x: 23, y: 70 }, fb: { x: 28, y: 90 }, dm: { x: 42, y: 50 }, cm: { x: 55, y: 35 }, am: { x: 66, y: 50 }, wg: { x: 68, y: 18 }, st: { x: 84, y: 50 } };
export const defaultFormation: FormationPlayer[] = [
  { playerId: "p1", label: "MV", role: "Goalkeeper", point: points.gk }, { playerId: "p2", label: "JB", role: "Centre Back", point: points.cb1 }, { playerId: "p3", label: "SO", role: "Centre Back", point: points.cb2 }, { playerId: "p4", label: "EH", role: "Fullback", point: points.fb }, { playerId: "p5", label: "TI", role: "Anchor", point: points.dm }, { playerId: "p6", label: "NM", role: "Mezzala", point: points.cm }, { playerId: "p7", label: "RD", role: "Creator", point: points.am }, { playerId: "p8", label: "LB", role: "Winger", point: points.wg }, { playerId: "p10", label: "MR", role: "Striker", point: points.st },
];

export type ClubState = { name: string; city: string; founded: number; division: string; points: number; position: number; budget: number; wageRoom: number; boardConfidence: number; morale: number; nextOpponent: string; nextMatchAt: string; mentality: Mentality; formation: FormationPlayer[]; match: { minute: number; homeGoals: number; awayGoals: number; phase: MatchPhase; events: MatchEvent[]; opponentPlan: OpponentPlan; opponentPressure: number; possession: number } ; market: { targets: MarketTarget[]; bids: Bid[]; scouting: string[] } };

const target = (p: Player, club: string, league: string, multiplier: number): MarketTarget => ({ ...p, id: `m-${p.id}`, club, league, asking: Math.round(p.value * multiplier), availability: multiplier < 1 ? "Interested" : "Difficult", scoutStatus: "Unscouted" });
const initialTargets = [target({ id: "x1", name: "Kian Doyle", position: "ST", age: 22, overall: 77, fitness: 92, form: 7.4, morale: 80, wage: 1900, value: 1450000, status: "Available" }, "Harbour Town", "National League One", 1.12), target({ id: "x2", name: "Milo Sato", position: "FB", age: 21, overall: 74, fitness: 95, form: 7.1, morale: 85, wage: 1600, value: 900000, status: "Available" }, "Northbridge", "National League One", .96), target({ id: "x3", name: "Bastien Morel", position: "CM", age: 25, overall: 80, fitness: 88, form: 7.8, morale: 81, wage: 3500, value: 1900000, status: "Available" }, "Lakeside FC", "Premier Division", 1.18), target({ id: "x4", name: "Ewan Price", position: "CB", age: 26, overall: 76, fitness: 90, form: 7.2, morale: 77, wage: 2400, value: 1100000, status: "Available" }, "Redminster", "National League One", 1.04)];

export const initialClub: ClubState = { name: "Riverside Athletic", city: "Northport", founded: 1912, division: "National League One", points: 31, position: 5, budget: 4200000, wageRoom: 18400, boardConfidence: 68, morale: 82, nextOpponent: "Crown Vale", nextMatchAt: "Saturday · 15:00", mentality: "Balanced", formation: structuredClone(defaultFormation), match: { minute: 0, homeGoals: 0, awayGoals: 0, phase: "idle", events: [], opponentPlan: "Mid Block", opponentPressure: 45, possession: 50 }, market: { targets: initialTargets, bids: [], scouting: [] } };
const store = globalThis as typeof globalThis & { __touchline26?: ClubState };
export function getClub() { store.__touchline26 ??= structuredClone(initialClub); return store.__touchline26; }
function commentary(club: ClubState, minute: number, seed: number, home: boolean, goal: boolean): MatchEvent { const team = home ? "Riverside" : club.nextOpponent; const lines = goal ? [`${team} finish the move with real conviction.`, `${team} find the gap between fullback and centre-half.`, `A patient move ends with ${team} making the breakthrough.`] : [`${team} circulate patiently, waiting for the midfield line to step out.`, `${team} attack the space behind the wide defender.`, `${team} win the second ball and build again.`]; return { id: `${minute}-${club.match.events.length}`, minute, kind: goal ? "Goal" : "Commentary", side: home ? "home" : "away", text: lines[seed % lines.length], detail: home ? `The ${club.mentality.toLowerCase()} plan creates the opening.` : `${club.nextOpponent} are using a ${club.match.opponentPlan.toLowerCase()}.` }; }
function updateOpponent(club: ClubState, seed: number) { const scoreDiff = club.match.homeGoals - club.match.awayGoals; if (scoreDiff > 0 && club.match.minute > 60) club.match.opponentPlan = "Protect Lead"; else if (club.mentality === "Assertive" && club.match.minute > 20) club.match.opponentPlan = seed % 2 ? "High Press" : "Overload Right"; else if (club.match.possession < 45) club.match.opponentPlan = "High Press"; else club.match.opponentPlan = "Mid Block"; club.match.opponentPressure = club.match.opponentPlan === "High Press" ? 72 : club.match.opponentPlan === "Protect Lead" ? 35 : 52; }
export function simulateTick() { const club = getClub(); if (club.match.phase !== "live") club.match = { ...club.match, minute: 0, homeGoals: 0, awayGoals: 0, phase: "live", events: [] }; club.match.minute = Math.min(90, club.match.minute + 5); const minute = club.match.minute; const seed = (minute * 29 + club.points * 7 + club.match.events.length * 13 + club.match.opponentPressure) % 100; updateOpponent(club, seed); const homeEdge = club.mentality === "Assertive" ? 0.6 : club.mentality === "Cautious" ? 0.46 : 0.53; club.match.possession = Math.max(32, Math.min(68, Math.round(50 + (homeEdge - .5) * 30 - (club.match.opponentPressure - 50) * .08))); const producesAction = seed > 56; if (producesAction) { const home = seed % 10 / 10 < homeEdge; const goal = seed > 93 || (home && seed > 85); const event = commentary(club, minute, seed, home, goal); club.match.events.unshift(event); if (goal) home ? club.match.homeGoals++ : club.match.awayGoals++; } else if (minute % 10 === 0) club.match.events.unshift({ id: `${minute}-t`, minute, kind: "Tactical", side: "away", text: `${club.nextOpponent} adjust their shape to ${club.match.opponentPlan.toLowerCase()}.`, detail: "The opposition coaching staff are reacting to the match state." }); if (minute >= 90) club.match.phase = "finished"; return club; }
export function setMentality(mentality: Mentality) { getClub().mentality = mentality; return getClub(); }
export function resetMatch() { const club = getClub(); club.match = { minute: 0, homeGoals: 0, awayGoals: 0, phase: "idle", events: [], opponentPlan: "Mid Block", opponentPressure: 45, possession: 50 }; return club; }
export function saveFormation(formation: FormationPlayer[]) { getClub().formation = formation; return getClub(); }
export function scoutPlayer(id: string) { const club = getClub(); const item = club.market.targets.find(t => t.id === id); if (item) { item.scoutStatus = "Report ready"; club.market.scouting = Array.from(new Set([...club.market.scouting, id])); } return club; }
export function submitBid(targetId: string, amount: number) { const club = getClub(); const item = club.market.targets.find(t => t.id === targetId); if (!item || amount <= 0 || amount > club.budget) throw new Error("Bid is not valid for the current market or budget."); const bid: Bid = { id: `bid-${Date.now()}`, targetId, amount, status: amount >= item.asking ? "Accepted" : "Countered", createdAt: new Date().toISOString() }; club.market.bids.unshift(bid); if (bid.status === "Accepted") club.budget -= amount; return club; }
